CREATE TABLE IF NOT EXISTS admUsr (
  ID INT UNSIGNED PRIMARY KEY,
  SessTyp INT UNSIGNED NOT NULL,
  FOREIGN KEY ( ID ) REFERENCES Usr ( ID ) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS inCareOf (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  UsrName VARCHAR(60) NOT NULL,
  UsrEmail VARCHAR(255) NOT NULL, /* email of the admin user who took care of the user most recently */
  UNIQUE ( UsrName )
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS pwParam (
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	rtrtDate DATE NOT NULL,
	pwExpires DATE NOT NULL,
	rtEvent ENUM('RespectAncestors','ThriceYearning') NOT NULL,
	rtTemple VARCHAR(60) NOT NULL,
	rtReason VARCHAR(60) NOT NULL,
	rtVenerable VARCHAR(40),
	rtZhaiZhu VARCHAR(60),
	rtShouDu VARCHAR(60),	
	lastRtrtDate DATE NOT NULL
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

