CREATE TABLE IF NOT EXISTS Usr (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  UsrName VARCHAR(60) NOT NULL,
  UsrPass VARCHAR(60) NOT NULL,
  UsrEmail VARCHAR(255) NOT NULL,
  UNIQUE ( UsrName ),
  UNIQUE ( UsrEmail )
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS UsrRst (
  ID INT UNSIGNED PRIMARY KEY,
  Token VARCHAR (60) UNIQUE NOT NULL,
  Expires DATETIME,
	FOREIGN KEY ( ID ) REFERENCES Usr ( ID )
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
